### ISSUE TITLE
/delete comand

### ISSUE THREAD

**Issue by vtimofeev01** [intel/video-analytics-serving#33]
I have made 

```
def delete_pipeline(instance_id, pipeline, version, video_analytics_serving, camera):
    """Fetch status of requested pipeline"""
    try:
        status_response = requests.delete(
            urljoin(video_analytics_serving, "/".join([pipeline, str(version), str(instance_id)])), timeout=TIMEOUT)
        if status_response.status_code == 200:
            return json.loads(status_response.text)
    except requests.exceptions.RequestException as request_error:
        output(camera, request_error)
    return None
```

but it raises a fault

```
2020-09-05 19:58:41,040 Exception on /pipelines/persons_detector_no_face/2/2 [DELETE]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/dist-packages/connexion/decorators/decorator.py", line 49, in wrapper
    return self.api.get_response(response, self.mimetype, request)
  File "/usr/local/lib/python3.6/dist-packages/connexion/apis/flask_api.py", line 136, in get_response
    return cls._get_response(response, mimetype=mimetype, extra_context={"url": flask.request.url})
  File "/usr/local/lib/python3.6/dist-packages/connexion/apis/abstract.py", line 277, in _get_response
    framework_response = cls._response_from_handler(response, mimetype, extra_context)
  File "/usr/local/lib/python3.6/dist-packages/connexion/apis/abstract.py", line 331, in _response_from_handler
    return cls._build_response(mimetype=mimetype, data=response, extra_context=extra_context)
  File "/usr/local/lib/python3.6/dist-packages/connexion/apis/flask_api.py", line 173, in _build_response
    data, status_code, serialized_mimetype = cls._prepare_body_and_status_code(data=data, mimetype=mimetype, status_code=status_code, extra_context=extra_context)
  File "/usr/local/lib/python3.6/dist-packages/connexion/apis/abstract.py", line 403, in _prepare_body_and_status_code
    body, mimetype = cls._serialize_data(data, mimetype)
  File "/usr/local/lib/python3.6/dist-packages/connexion/apis/flask_api.py", line 190, in _serialize_data
    body = cls.jsonifier.dumps(data)
  File "/usr/local/lib/python3.6/dist-packages/connexion/jsonifier.py", line 44, in dumps
    return self.json.dumps(data, **kwargs) + '\n'
  File "/usr/local/lib/python3.6/dist-packages/flask/json/__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.6/json/encoder.py", line 430, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.6/json/encoder.py", line 437, in _iterencode
    o = _default(o)
  File "/usr/local/lib/python3.6/dist-packages/connexion/apps/flask_app.py", line 138, in default
    return json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python3.6/dist-packages/flask/json/__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'State' is not JSON serializable
```

**Comment by nnshah1** [comment]
@vtimofeev01 Can you confirm what version of VA serving you are using? I believe this was address in the 0.3.1 release - do you see it in the latest?

**Comment by vtimofeev01** [comment]
it is so
thank U
