### ISSUE TITLE
Some errors about sample request.

### ISSUE THREAD

**Issue by lsydd** [intel/video-analytics-serving#6]
# Sample request:
I’m trying to use your GitHub repository :video-analytics-serving. But the service shows some error when I try to run the sample code.
My environment is:
Intel Xeon Phi CPU7285;  Ubuntu 18.04.3;    Docker 19.03.2 build 6a30dfc.
0. It seems that I've succesfully built the gstreamer and ffmpeg version from your dockerfile.
~~~markdown
REPOSITORY                               TAG                 IMAGE ID            CREATED             SIZE
video_analytics_serving_gstreamer        latest              9f6cc71d9875        6 days ago          1.14GB
video_analytics_serving_ffmpeg           latest              63c8771c70f3        6 days ago          457MB
video_analytics_serving_ffmpeg_base      latest              dd5e7f92758e        6 days ago          220MB
<none>                                   <none>              c3532d0ed62c        6 days ago          4.44GB
video_analytics_serving_gstreamer_base   latest              15bbd8f30cfc        6 days ago          973MB
<none>                                   <none>              8668928d50bd        6 days ago          7.44GB
ubuntu                                   18.04               775349758637        4 weeks ago         64.2MB
<none>                                   <none>              eb772b2d5623        7 weeks ago         852MB

~~~ 

1. When I run the Gstreamer and the sample post:
~~~markdown
curl 10.239.43.221:8080/pipelines/emotion_recognition/1 -X POST -H 'Content-Type: application/json' -d '{ "source": { "uri": "https://github.com/intel-iot-devkit/sample-videos/blob/master/head-pose-face-detection-male.mp4?raw=true", "type": "uri" }, "destination": { "type": "file", "path": "/tmp/results1.txt", "format":"stream"}}'
~~~
I can find results1.txt at /tmp, while noting is written into it. 
The status is ‘QUEUED’ for several minutes, then the docker will corrupt.
~~~markdown
curl 10.239.43.221:8080/pipelines/emotion_recognition/1/1/status -X GET
~~~
~~~markdown
{
  "avg_fps": 0,
  "elapsed_time": 128.1189136505127,
  "id": 1,
  "start_time": 1574865363.3796282,
  "state": "QUEUED"
}
~~~

~~~markdown
(gst-plugin-scanner:12): GStreamer-WARNING **: 13:25:53.775: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstpython.cpython-36m-x86_64-linux-gnu.so': libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
{"levelname": "ERROR", "asctime": "2019-11-27 13:25:55,487", "message": "Error loading FFmpeg: ffmpeg not installed\n", "name": "PipelineManager"}
{"levelname": "INFO", "asctime": "2019-11-27 13:25:55,488", "message": "Loading Pipelines from Config Path /home/video-analytics/app/server/openapi_server/../../../pipelines/gstreamer", "name": "PipelineManager"}
{"levelname": "INFO", "asctime": "2019-11-27 13:25:55,697", "message": "Completed Loading Pipelines", "name": "PipelineManager"}
{"levelname": "INFO", "asctime": "2019-11-27 13:25:55,698", "message": "Loading Models from Path /home/video-analytics/models", "name": "ModelManager"}
{"levelname": "INFO", "asctime": "2019-11-27 13:25:55,714", "message": "Completed Loading Models", "name": "ModelManager"}
{"levelname": "INFO", "asctime": "2019-11-27 13:25:56,279", "message": "Starting Tornado Server on port: 8080", "name": "main"}
{"levelname": "INFO", "asctime": "2019-11-27 13:26:57,836", "message": "Creating Instance of Pipeline emotion_recognition/1", "name": "PipelineManager"}
{"levelname": "ERROR", "asctime": "2019-11-27 13:26:57,937", "message": "Error on Pipeline <built-in function id>: gst-resource-error-quark: metapublish initialization failed (2)", "name": "GSTPipeline"}
{"levelname": "INFO", "asctime": "2019-11-27 13:27:18,242", "message": "Creating Instance of Pipeline emotion_recognition/1", "name": "PipelineManager"}
./docker-entrypoint.sh: line 3:     6 Segmentation fault      (core dumped) python3 -m openapi_server $@

(gst-plugin-scanner:12): GStreamer-WARNING **: 14:35:49.573: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstpython.cpython-36m-x86_64-linux-gnu.so': libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
{"levelname": "ERROR", "asctime": "2019-11-27 14:35:51,272", "message": "Error loading FFmpeg: ffmpeg not installed\n", "name": "PipelineManager"}
{"levelname": "INFO", "asctime": "2019-11-27 14:35:51,273", "message": "Loading Pipelines from Config Path /home/video-analytics/app/server/openapi_server/../../../pipelines/gstreamer", "name": "PipelineManager"}
{"levelname": "INFO", "asctime": "2019-11-27 14:35:51,474", "message": "Completed Loading Pipelines", "name": "PipelineManager"}
{"levelname": "INFO", "asctime": "2019-11-27 14:35:51,475", "message": "Loading Models from Path /home/video-analytics/models", "name": "ModelManager"}
{"levelname": "INFO", "asctime": "2019-11-27 14:35:51,490", "message": "Completed Loading Models", "name": "ModelManager"}
{"levelname": "INFO", "asctime": "2019-11-27 14:35:52,070", "message": "Starting Tornado Server on port: 8080", "name": "main"}
{"levelname": "INFO", "asctime": "2019-11-27 14:36:03,093", "message": "Creating Instance of Pipeline emotion_recognition/1", "name": "PipelineManager"}
{"levelname": "INFO", "asctime": "2019-11-27 14:38:19,886", "message": "Creating Instance of Pipeline emotion_recognition/1", "name": "PipelineManager"}
{"levelname": "INFO", "asctime": "2019-11-27 14:39:05,668", "message": "Creating Instance of Pipeline object_detection/1", "name": "PipelineManager"}
./docker-entrypoint.sh: line 3:     6 Segmentation fault      (core dumped) python3 -m openapi_server $@
~~~
2. Then I run ffmpeg as pipelines. The docker doesn’t corrupt, but I still cannot get the result.
The status is ‘RUNNING’ for about 10 seconds, then it will be ‘ERROR’.
~~~markdown
face@fly:/tmp$ curl 10.239.43.221:8080/pipelines/emotion_recognition/1/1/status -X GET
~~~
~~~markdown
{
  "avg_fps": 0,
  "elapsed_time": 12.269392251968384,
  "id": 1,
  "start_time": 1574862817.2551162,
  "state": "RUNNING"
}
face@fly:/tmp$ curl 10.239.43.221:8080/pipelines/emotion_recognition/1/1/status -X GET
{
  "avg_fps": 0,
  "elapsed_time": 14.299017429351807,
  "id": 1,
  "start_time": 1574862817.2551162,
  "state": "ERROR"
}
~~~
3. At last, I get into the docker, and just do as the /home/video-analytics/samples/README.md.
After python3 sample.py, it returns some error as below:
~~~markdown
root@d8a13277aeb8:/home/video-analytics/samples# python3 sample.py
Launching with options:
Namespace(destination='/home/video-analytics/samples/results.txt', pipeline='object_detection', repeat=1, source='file:///home/video-analytics/samples/pinwheel.ts', verbose=True)
Starting Pipeline: http://localhost:8080/pipelines/object_detection/1
Traceback (most recent call last):
  File "sample.py", line 215, in <module>
    main()
  File "sample.py", line 212, in main
    launch_pipelines(options)
  File "sample.py", line 198, in launch_pipelines
    verbose=options.verbose)
  File "sample.py", line 81, in read_detection_results
    with open(destination) as detection_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/video-analytics/samples/results.txt'
~~~
Would you help me to resolve these issues?

**Comment by cgdougla** [comment]
All of these samples use Intel OpenVino. Unfortunately, Xeon Phi is not supported hardware for running OpenVino. See [here](https://software.intel.com/en-us/openvino-toolkit/hardware) for supported hardware

**Comment by lsydd** [comment]
Thanks, I use a server with Xeon processor instead and get the result in /temp.
